# Generated by Django 4.2.10 on 2024-09-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_department_posts_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='description',
        ),
        migrations.AddField(
            model_name='posts',
            name='catalog_number_or_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(error_messages={'unique': 'この部署名はすでに存在します。別の名前を入力してください。'}, max_length=100, unique=True),
        ),
    ]
